spring:
  security:
    oauth2:
      resourceserver:
        clientId: app-resource-server
        clientSecret:
        jwt:
          issuer-uri: http:/[host]:[port]/auth/realms/[realm]
          jwk-set-uri: http://[host]:[port]/auth/realms/[realm]/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        security: DEBUG